(()=>{'use strict';const $=id=>document.getElementById(id),dialogs=EN_DIALOGUES;let index=0,step=0,actor='guest';
const key=()=> 'foxora:en:writing:'+actor+':'+dialogs[0].level+':'+index;
function save(){try{localStorage.setItem(key(),$('freeAnswer').value);$('draftStatus').textContent='Entwurf gespeichert.';}catch(_){$('draftStatus').textContent='Der Entwurf konnte nicht gespeichert werden.';}}
function show(s){step=s;$('dialogueAudio').pause();$('sentenceAudio').pause();for(let i=0;i<3;i++)$('step'+i).hidden=s!==i;document.querySelectorAll('[data-step]').forEach(b=>{if(Number(b.dataset.step)===s)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current');});$('stepLabel').textContent='Schritt '+(s+1)+' von 3';$('stepBack').hidden=s===0;$('stepNext').hidden=s===2;$('nextSituation').hidden=s!==2;$('stepNext').textContent=s===0?'Weiter zum Schreiben →':'Weiter zum Nachsprechen →';}
function render(){const d=dialogs[index];show(0);$('situationTitle').textContent=d.title;$('dialogueAudio').src='audio/jetzt-anwenden/'+d.file;$('dialogueAudio').load();$('audioStatus').textContent='';$('transcript').replaceChildren();$('listeningFeedback').replaceChildren();d.turns.forEach(t=>{const p=document.createElement('p'),en=document.createElement('span'),de=document.createElement('span');en.lang='en';en.textContent=t.speaker+': '+t.en;de.className='de';de.textContent=t.de;p.append(en,de);$('transcript').append(p)});$('transcript').parentElement.open=false;
const form=$('listeningQuiz');form.replaceChildren();d.questions.forEach((q,i)=>{const f=document.createElement('fieldset'),l=document.createElement('legend');l.textContent=(i+1)+'. '+q.prompt;f.append(l);q.options.forEach((text,j)=>{const label=document.createElement('label'),r=document.createElement('input');r.type='radio';r.name='q'+i;r.value=j;r.required=true;label.append(r,document.createTextNode(' '+text));f.append(label)});form.append(f)});const submit=document.createElement('button');submit.type='submit';submit.textContent='Verständnis prüfen';form.append(submit);form.onsubmit=e=>{e.preventDefault();if(!form.reportValidity())return;let count=0;const feedback=$('listeningFeedback');feedback.replaceChildren();d.questions.forEach((q,i)=>{const ok=Number(new FormData(form).get('q'+i))===q.answer;if(ok)count++;const p=document.createElement('p');p.textContent=(ok?'✓ ':'↻ ')+q.why+' Lösung: '+q.options[q.answer];feedback.append(p)});const p=document.createElement('p');p.textContent=count+' von 3 richtig. Du kannst die Aufnahme und Fragen wiederholen.';feedback.prepend(p);};
$('writingTask').textContent=d.writing;try{$('freeAnswer').value=localStorage.getItem(key())||'';}catch(_){$('freeAnswer').value='';}$('writingModel').textContent=d.model;$('modelBox').hidden=true;$('draftStatus').textContent='';$('sentenceClips').replaceChildren();$('sentenceAudio').pause();$('sentenceAudio').removeAttribute('src');$('sentenceAudio').hidden=true;$('sentenceStatus').textContent='';d.turns.forEach((t,i)=>{const p=document.createElement('div');p.className='panel';const en=document.createElement('p');en.lang='en';en.textContent=t.en;const de=document.createElement('p');de.className='de';de.textContent=t.de;const b=document.createElement('button');b.type='button';b.className='secondary';b.textContent='▶ Satz anhören';b.onclick=()=>{$('dialogueAudio').pause();const audio=$('sentenceAudio');audio.src='audio/jetzt-anwenden/'+d.file.replace('-dialogue.mp3','-phrase-'+String(i+1).padStart(2,'0')+'.mp3');audio.hidden=false;audio.play().catch(()=>{$('sentenceStatus').textContent='Diese Satzaufnahme ist noch nicht verfügbar.';});};p.append(en,de,b);$('sentenceClips').append(p)});}
$('dialogueAudio').onerror=()=>{$('audioStatus').textContent='Die Aufnahme ist noch nicht verfügbar. Du kannst den Dialogtext bereits lesen.';};$('dialogueAudio').onplay=()=>{$('sentenceAudio').pause();};$('sentenceAudio').onerror=()=>{$('sentenceStatus').textContent='Diese Satzaufnahme ist noch nicht verfügbar.';};dialogs.forEach((d,i)=>{const b=document.createElement('button');b.type='button';b.className='secondary';b.textContent=d.title;b.onclick=()=>{save();index=i;render();};$('situations').append(b);});document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{save();show(Number(b.dataset.step));});$('stepBack').onclick=()=>{save();show(step-1);};$('stepNext').onclick=()=>{save();show(step+1);};$('nextSituation').onclick=()=>{save();index=(index+1)%dialogs.length;render();};$('saveDraft').onclick=save;$('compareDraft').onclick=()=>{$('modelBox').hidden=false;};FRLearning.ready.then(()=>{actor=FRLearning.account;render();});window.addEventListener('frlearningchange',()=>{if(actor!==FRLearning.account){actor=FRLearning.account;if(dialogs[0].level>1)location.reload();else render();}});
})();
