(()=>{'use strict';
const D=window.EN_LESSON,$=id=>document.getElementById(id);
const norm=s=>String(s??'').normalize('NFC').toLowerCase().replace(/[’‘]/g,"'").replace(/\s+/g,' ').trim().replace(/[.!?]+$/,'');
window.ENAnswers={norm,check:(own,right)=>norm(own)===norm(right)};
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
if(!D)return;
let queue=[],at=0,score=0,attempts=0,review=false,locked=false,finished=false,selected=[],answers=[],deadline=0,ticker,owner=null,phase=0;
const exam=D.kind==='exam',session=D.kind==='session';
function choose(){let pool=D.questions;if(session)return [...pool].sort((a,b)=>FRLearning.dueScore(b.sourceModule,b.sourceId)-FRLearning.dueScore(a.sourceModule,a.sourceId)).slice(0,30);const params=new URLSearchParams(location.search),ids=(params.get('review')||'').split(',').filter(Boolean);if(ids.length){const chosen=pool.filter(q=>ids.includes(q.id));if(chosen.length)return shuffle(chosen).slice(0,15);}if(exam){const topics=[...new Set(pool.map(q=>q.topic))];return topics.flatMap(topic=>shuffle(pool.filter(q=>q.topic===topic)).slice(0,D.count/topics.length));}const old=FRLearning.moduleData(D.module).wrongIds||[];const weak=shuffle(pool.filter(q=>old.includes(Number(q.id)))).slice(0,3);const used=new Set(weak.map(q=>q.id));return shuffle([...weak,...shuffle(pool.filter(q=>!used.has(q.id))).slice(0,15-weak.length)]);}
function own(){return $('answer').value;}
function details(q,value){return {own:value,right:q.right,prompt:q.prompt,explanation:q.explanation,topic:q.topic,file:q.file,type:q.type,unanswered:!value.trim()};}
function record(q,value,ok,repeat){FRLearning.record(q.sourceModule||D.module,q.sourceId||q.id,ok,repeat,q.prompt,details(q,value));}
function display(){if(finished)return;const q=queue[at];if(!q){end();return;}locked=false;selected=[];$('answer').value=exam?(answers[at]||''):'';$('answer').readOnly=q.type==='order';$('answer').hidden=q.type==='choice';$('answerLabel').hidden=q.type==='choice';$('choices').replaceChildren();$('tokens').replaceChildren();$('feedback').hidden=true;$('check').hidden=exam;$('check').disabled=false;$('continue').hidden=!exam;$('continue').textContent=exam?'Antwort speichern →':'Weiter →';$('position').textContent=(session?(phase===0?'Wiederholen · ':'Neue Aufgaben · '):'')+'Aufgabe '+(at+1)+(exam?' von '+queue.length:'');$('question').textContent=q.prompt;$('question').focus();$('wordHelp').hidden=!q.words?.length||q.type==='order';$('wordHelp').textContent=q.words?.length?'Worthilfe: '+shuffle(q.words).join(' · '):'';
if(q.type==='choice'){shuffle(q.options).forEach(opt=>{const label=document.createElement('label'),input=document.createElement('input');label.className='choice';input.type='radio';input.name='choice';input.value=opt;input.checked=exam&&answers[at]===opt;input.onchange=()=>{$('answer').value=opt;};label.append(input,document.createTextNode(opt));$('choices').append(label)});}
if(q.type==='order'){const tokens=shuffle(q.words.map((text,id)=>({text,id})));const update=()=>{$('answer').value=selected.map(id=>tokens.find(t=>t.id===id).text).join(' ');};tokens.forEach(t=>{const b=document.createElement('button');b.type='button';b.className='secondary';b.textContent=t.text;b.onclick=()=>{selected.push(t.id);b.disabled=true;update();};b.dataset.token=t.id;$('tokens').append(b)});const undo=document.createElement('button');undo.type='button';undo.className='secondary';undo.textContent='↶ Letztes Wort entfernen';undo.onclick=()=>{const id=selected.pop();const b=$('tokens').querySelector('[data-token="'+id+'"]');if(b)b.disabled=false;update();};$('tokens').append(undo);if(exam&&answers[at]){$('answer').value=answers[at];}}
$('examBack').hidden=!exam||at===0;$('endExam').hidden=!exam;
}
function end(){if(finished)return;finished=true;clearInterval(ticker);$('quiz').hidden=true;$('result').hidden=false;const list=$('resultDetails');list.replaceChildren();if(exam){score=0;queue.forEach((q,i)=>{const value=answers[i]||'',ok=ENAnswers.check(value,q.right);if(ok)score++;record(q,value,ok,false);const p=document.createElement('div');p.className='feedback '+(ok?'correct':'wrong');const title=document.createElement('p');title.textContent=(ok?'✓ ':'↻ ')+q.prompt;const text=document.createElement('p');text.textContent='Deine Antwort: '+(value||'Keine Antwort')+' · Lösung: '+q.right+' · '+q.explanation;p.append(title,text);if(q.file){const a=document.createElement('a');a.href=q.file+'?review='+encodeURIComponent(q.sourceId||q.id);a.textContent='Passende Übung öffnen →';p.append(a);}list.append(p)});attempts=queue.length;}
const pct=attempts?Math.round(score/attempts*100):0;FRLearning.finish(D.module,pct);$('resultText').textContent=score+' von '+attempts+' ersten Antworten richtig ('+pct+' %). Wiederholungen sind getrennt gezählt.';if(D.theory){$('theoryLink').href=D.theory;$('theoryLink').hidden=false;}if(D.exam){$('examLink').href=D.exam;$('examLink').hidden=false;}paintFox(pct>=70);
}
function paintFox(ok){const fox=$('exerciseFox');if(fox)fox.src=ok?'fuchs-richtig.png':'fuchs-falsch.png';}
function check(){if(locked||finished)return;const q=queue[at],value=own();if(!value.trim()){$('feedback').hidden=false;$('feedback').textContent='Wähle eine Antwort oder fülle das Antwortfeld aus.';return;}locked=true;const ok=ENAnswers.check(value,q.right),repeat=!!q.repeat;record(q,value,ok,repeat);if(!repeat){attempts++;if(ok)score++;}if(!ok&&!repeat&&!session)queue.push({...q,repeat:true});$('feedback').hidden=false;$('feedback').className='feedback '+(ok?'correct':'wrong');$('feedback').textContent=(ok?'✓ Richtig. ':'↻ Lösung: '+q.right+'. ')+q.explanation;$('check').disabled=true;$('choices').querySelectorAll('input').forEach(e=>e.disabled=true);$('tokens').querySelectorAll('button').forEach(e=>e.disabled=true);$('answer').readOnly=true;$('continue').hidden=false;paintFox(ok);}
function move(){if(exam)answers[at]=own();at++;if(session&&at>=queue.length){queue.push(...shuffle(D.questions).slice(0,30));}display();}
function tick(){const remaining=Math.max(0,Math.ceil((deadline-Date.now())/1000));$('timer').textContent=(session?(phase===0?'5 Minuten Wiederholung · ':'10 Minuten neue Aufgaben · '):'Prüfungszeit · ')+Math.floor(remaining/60)+':'+String(remaining%60).padStart(2,'0');if(session&&phase===0&&Date.now()>=deadline-10*60*1000){phase=1;queue=shuffle(D.newQuestions||D.questions).slice(0,60);at=0;display();}if(!remaining)end();}
function start(){finished=false;owner=FRLearning.account;at=0;score=0;attempts=0;answers=[];phase=0;queue=choose();$('quiz').hidden=false;$('result').hidden=true;clearInterval(ticker);if(exam||session){deadline=Date.now()+(session?15:30)*60*1000;ticker=setInterval(tick,500);$('timer').hidden=false;tick();}display();}
$('check').onclick=check;$('continue').onclick=move;$('answer').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();if(exam||locked)move();else check();}};$('examBack').onclick=()=>{answers[at]=own();at--;display();};$('endExam').onclick=()=>{if(confirm('Prüfung jetzt abgeben? Nicht beantwortete Aufgaben zählen als falsch.')){answers[at]=own();end();}};$('restart').onclick=session?()=>location.reload():start;
FRLearning.ready.then(start);window.addEventListener('frlearningchange',()=>{if(owner!==null&&owner!==FRLearning.account){clearInterval(ticker);owner=FRLearning.account;if(D.level>1||exam||session){location.reload();}else start();}});
})();
