(()=>{'use strict';const $=id=>document.getElementById(id);let premium=false,actor=null;
$('chooseGrammar').onclick=()=>{$('Grammar').hidden=false;$('Alltag').hidden=true;$('chooseGrammar').setAttribute('aria-expanded','true');$('chooseEveryday').setAttribute('aria-expanded','false');};$('chooseEveryday').onclick=()=>{$('Grammar').hidden=true;$('Alltag').hidden=false;$('chooseEveryday').setAttribute('aria-expanded','true');$('chooseGrammar').setAttribute('aria-expanded','false');};
function progress(){const s=FRLearning.summary();$('todayCount').textContent=s.day.answered;$('dailyProgress').value=Math.min(15,s.day.answered);$('streakCount').textContent=s.streak;$('totalCount').textContent=s.total;$('correctCount').textContent=s.correct+' correct';$('progressStatus').textContent=FRLearning.status;const el=$('learningSyncStatus');if(el)el.textContent=FRLearning.status;analysis();}
function analysis(){const box=$('analysis');box.replaceChildren();if(!premium){box.textContent='Detailed error review and your individual learning plan require Premium.';return;}const modules=FRLearning.summary().modules,rows=DE_EN_CATALOG.filter(m=>m.kind==='lesson').map(m=>{const d=modules[m.module];return {...m,attempts:d?.answered||0,correct:d?.correct||0,wrong:Object.entries(d?.questions||{}).filter(([,q])=>q.wrong>0&&q.strength<2).map(([id])=>id)};}).filter(m=>m.attempts>0).sort((a,b)=>b.wrong.length-a.wrong.length||(a.correct/a.attempts-b.correct/b.attempts));if(!rows.length){box.textContent='Complete some exercises first. Your next three learning steps will then appear here.';return;}rows.slice(0,3).forEach((m,i)=>{const recent=FRLearning.events.filter(e=>e.kind==='answer'&&e.module===m.module&&!e.review).slice(-20);const detail=document.createElement('p');detail.className='note';detail.textContent='Recent results: '+recent.filter(e=>e.ok).length+' of '+recent.length+' first answers correct'+(recent.length<5?' · Too few answers for a reliable estimate.':'.');box.append(detail);const errors=FRLearning.events.filter(e=>e.kind==='answer'&&e.module===m.module&&!e.ok&&e.details?.right).slice(-3);for(const e of errors){const example=document.createElement('div');example.className='feedback';const own=document.createElement('p');own.textContent='Your answer: '+(e.details.own||'No answer');const right=document.createElement('p');right.textContent='Suggested answer: '+e.details.right;const why=document.createElement('p');why.className='note';why.textContent=e.details.explanation;example.append(own,right,why);box.append(example);}const p=document.createElement('p'),a=document.createElement('a');a.href=m.file+(m.wrong.length?'?review='+encodeURIComponent(m.wrong.slice(0,10).join(',')):'');a.textContent=(i+1)+'. '+m.title+' · Level '+m.level;p.append(a);const note=document.createElement('span');note.className='de';note.textContent=m.wrong.length?'Review '+m.wrong.length+' tasks with unresolved mistakes.':'Consolidate this topic with a new round.';p.append(note);box.append(p)});}
async function status(){const owner=FRLearning.account;actor=owner;premium=false;if(owner==='guest'){$('premiumStatus').textContent='Sign in to check your Premium status.';progress();return;}try{const s=await FRPremium.status();if(owner!==FRLearning.account)return;premium=!!s.premium;$('premiumStatus').textContent=premium?'Premium is active.':'No active Premium subscription. Remaining: '+s.remaining+' free 15-minute starts this week.';}catch(e){$('premiumStatus').textContent=e.message;}progress();}
for(const [id,fn] of [['premiumBuy',()=>FRPremium.checkout()],['premiumManage',()=>FRPremium.portal()]]){$(id).onclick=async()=>{$(id).disabled=true;try{await fn();}catch(e){$('premiumStatus').textContent=e.message;}finally{$(id).disabled=false;}};}
FRLearning.ready.then(()=>{progress();status();});window.addEventListener('frlearningchange',()=>{progress();if(actor!==FRLearning.account)status();});
})();

(()=>{const fox=document.getElementById('foxMascot'),bubble=document.getElementById('foxBubble');const tips=['A little practice every day makes a difference.','German nouns start with a capital letter.','Learn each noun together with its article.','Try saying one complete German sentence aloud.'];if(fox)fox.onclick=()=>{bubble.textContent=tips[Math.floor(Math.random()*tips.length)];};async function greet(){let name='';try{const {data}=await FRLearning.client.auth.getUser();name=data.user?.user_metadata?.name||'';}catch{}bubble.textContent=(name?name+', ':'')+'Hello! Ready for a little German practice?';}FRLearning.ready.then(greet);window.addEventListener('frlearningchange',greet);})();
