(()=>{'use strict';const $=id=>document.getElementById(id),dialogs=DE_EN_DIALOGUES;let index=0,step=0,actor='guest';
const key=()=> 'foxora:de-en:writing:'+actor+':'+dialogs[0].level+':'+index;
function save(){try{localStorage.setItem(key(),$('freeAnswer').value);$('draftStatus').textContent='Draft saved.';}catch(_){$('draftStatus').textContent='The draft could not be saved.';}}
function show(s){step=s;$('dialogueAudio').pause();$('sentenceAudio').pause();for(let i=0;i<3;i++)$('step'+i).hidden=s!==i;document.querySelectorAll('[data-step]').forEach(b=>{if(Number(b.dataset.step)===s)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current');});$('stepLabel').textContent='Step '+(s+1)+' of 3';$('stepBack').hidden=s===0;$('stepNext').hidden=s===2;$('nextSituation').hidden=s!==2;$('stepNext').textContent=s===0?'Continue to writing →':'Continue to speaking →';}
function render(){const d=dialogs[index];show(0);$('situationTitle').textContent=d.title;$('dialogueAudio').src='audio/jetzt-anwenden/'+d.file;$('dialogueAudio').load();$('audioStatus').textContent='';$('transcript').replaceChildren();$('listeningFeedback').replaceChildren();d.turns.forEach(t=>{const p=document.createElement('p'),en=document.createElement('span'),de=document.createElement('span');en.lang='de';en.textContent=t.speaker+': '+t.de;de.className='de';de.textContent=t.en;p.append(en,de);$('transcript').append(p)});$('transcript').parentElement.open=false;
const form=$('listeningQuiz');form.replaceChildren();d.questions.forEach((q,i)=>{const f=document.createElement('fieldset'),l=document.createElement('legend');l.textContent=(i+1)+'. '+q.prompt;f.append(l);q.options.forEach((text,j)=>{const label=document.createElement('label'),r=document.createElement('input');r.type='radio';r.name='q'+i;r.value=j;r.required=true;label.append(r,document.createTextNode(' '+text));f.append(label)});form.append(f)});const submit=document.createElement('button');submit.type='submit';submit.textContent='Check understanding';form.append(submit);form.onsubmit=e=>{e.preventDefault();if(!form.reportValidity())return;let count=0;const feedback=$('listeningFeedback');feedback.replaceChildren();d.questions.forEach((q,i)=>{const ok=Number(new FormData(form).get('q'+i))===q.answer;if(ok)count++;const p=document.createElement('p');p.textContent=(ok?'✓ ':'↻ ')+q.why+' Answer: '+q.options[q.answer];feedback.append(p)});const p=document.createElement('p');p.textContent=count+' of 3 correct. You can replay the audio and retry the questions.';feedback.prepend(p);};
$('writingTask').textContent=d.writing;try{$('freeAnswer').value=localStorage.getItem(key())||'';}catch(_){$('freeAnswer').value='';}$('writingModel').textContent=d.model;$('modelBox').hidden=true;$('draftStatus').textContent='';$('sentenceClips').replaceChildren();$('sentenceAudio').pause();$('sentenceAudio').removeAttribute('src');$('sentenceAudio').hidden=true;$('sentenceStatus').textContent='';d.turns.forEach((t,i)=>{const p=document.createElement('div');p.className='panel';const en=document.createElement('p');en.lang='de';en.textContent=t.de;const de=document.createElement('p');de.className='de';de.textContent=t.en;const b=document.createElement('button');b.type='button';b.className='secondary';b.textContent='▶ Play sentence';b.onclick=()=>{$('dialogueAudio').pause();const audio=$('sentenceAudio');audio.src='audio/jetzt-anwenden/'+d.file.replace('-dialogue.mp3','-phrase-'+String(i+1).padStart(2,'0')+'.mp3');audio.hidden=false;audio.play().catch(()=>{$('sentenceStatus').textContent='This sentence recording is not available yet.';});};p.append(en,de,b);$('sentenceClips').append(p)});}
$('dialogueAudio').onerror=()=>{$('audioStatus').textContent='The recording is not available yet. You can read the dialogue already.';};$('dialogueAudio').onplay=()=>{$('sentenceAudio').pause();};$('sentenceAudio').onerror=()=>{$('sentenceStatus').textContent='This sentence recording is not available yet.';};dialogs.forEach((d,i)=>{const b=document.createElement('button');b.type='button';b.className='secondary';b.textContent=d.title;b.onclick=()=>{save();index=i;render();};$('situations').append(b);});document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{save();show(Number(b.dataset.step));});$('stepBack').onclick=()=>{save();show(step-1);};$('stepNext').onclick=()=>{save();show(step+1);};$('nextSituation').onclick=()=>{save();index=(index+1)%dialogs.length;render();};$('saveDraft').onclick=save;$('compareDraft').onclick=()=>{$('modelBox').hidden=false;};FRLearning.ready.then(()=>{actor=FRLearning.account;render();});window.addEventListener('frlearningchange',()=>{if(actor!==FRLearning.account){actor=FRLearning.account;if(dialogs[0].level>1)location.reload();else render();}});
})();
